### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by abitdodgy** [duartejc/mailchimp#8]
@duartejc hi there, just wondering if this lib is production ready. I noticed it wasn't listed on hex.

**Comment by duartejc** [comment]
Hi @abitdodgy! I heard of some folks using it in production. I`m not working that much on this project at all. It`s on Hex actually: https://hex.pm/packages/mailchimp

**Comment by maennchen** [comment]
@abitdodgy I use it in production. That's also why I made contributions. It works for us, but I can't ensure that all use cases work properly. If there are problems, they should be easy to fix though.
